### ISSUE TITLE
cannot access login screen

### ISSUE THREAD

**Issue by hanabadler** [jitsucom/jitsu#1089] opened 2024-02-19 16:57 UTC
Hi community
i"m trying to start jitsu on ubuntu 20 (aws EC2 t3.large)
i followed the getting started guideline step to step.
using the docker-compose 
i have modified the .env file and run docker-compose up
all is running
when trying to access the ip:3000 the docker console return the followng error:

https://next-auth.js.org/errors#client_fetch_error fetch failed {
docker-console-1            |
docker-console-1            |   error: {
docker-console-1            |     message: 'fetch failed',
docker-console-1            |     stack: 'TypeError: fetch failed\n' +
docker-console-1            |       '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
docker-console-1            |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
docker-console-1            |     name: 'TypeError'
docker-console-1            |   },
docker-console-1            |   url: 'http://XXX.XXX.XXX.XXX:3000/api/auth/providers',
docker-console-1            |   message: 'fetch failed'
docker-console-1            | }

the .env file is  (IP masked)

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 	REQUIRED PARAMETERS, PLEASE READ INSTRUCTIONS THOROUGHLY
# See https://docs.jitsu.com/self-hosting/quick-start/ for more details
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Password and login of an *initial* admin user of Jitsu UI. After initial login, you must change your password!
# You can keep those variable empty if you are configuring Jitsu UI via Github auth (see below). In this case first
# authorized user will be granted a full access to Jitsu UI.
SEED_USER_EMAIL=admin@myadmin.com
SEED_USER_PASSWORD=1q2w3e4r!

# Domain name of your Jitsu server where events will be sent. E.g. https://jitsu.mycompany.com or http://localhost:8080
JITSU_INGEST_PUBLIC_URL=http://XXX.XXX.XXX.XXX:8080

# Public URL of your Jitsu UI. E.g. https://jitsu.mycompany.com or http://localhost:3000
JITSU_PUBLIC_URL=http://XXX.XXX.XXX.XXX:3000/

#### Secrets ###
# It is highly recommended to generate random values for those variables.
# You can use `openssl rand -hex 32` to generate random values.

CONSOLE_TOKEN=5bf6e8e563327221999c2ffa22641fffbc17238f256837b2e71db6488693f653
BULKER_TOKEN=3a16cc23357c4e339063016c3fef485050f7dfa533f7a35d8cdca412dc45e378
SYNCCTL_TOKEN=644f2ecf89e6e4d321e06f56f49f7e53bd421066666ab07c8a3a9295b3770513
POSTGRES_PASSWORD=228ddf14c0bcbb8ebacfccbfd2152a249c96d693509b5feb799ec8e184b5ad80

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 	OPTIONAL PARAMETERS
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

JITSU_UI_PORT=3000
JITSU_INGEST_PORT=8080

# If you want to have more than one user for Jitsu UI, this could be done via delegating auth to github.
# You need to create a new Github OAuth app and set those variables accordingly.
#GITHUB_CLIENT_ID=
#GITHUB_CLIENT_SECRET=

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# 	Connectors specific
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

SYNCS_ENABLED=false
EXTERNAL_BULKER_HOST=host.minikube.internal
EXTERNAL_BULKER_PORT=3042

# sync controller is running using host network to access 'minikube' w/o problems.
EXTERNAL_SYNCS_PORT=3043

#postgres host how it is reachable from k8s cluster
EXTERNAL_POSTGRES_HOST=host.minikube.internal
EXTERNAL_POSTGRES_PORT=5432

SYNCCTL_KUBERNETES_CLIENT_CONFIG=
# to use non-default k8s context
SYNCCTL_KUBERNETES_CONTEXT=
# For syncs scheduling
# google service account key
GOOGLE_SCHEDULER_KEY=
# for Google Ads connector
GOOGLE_ADS_DEVELOPER_TOKEN=

here is the screen shot

![image](https://github.com/jitsucom/jitsu/assets/3824585/7039dc37-ebaa-4795-89f3-281318632140)

Can you help explain what can be the problem?

thanks
Hana

**Comment by vklimontovich** [comment] 2024-02-19 17:21
Would you mind sharing stacktrace? 

![CleanShot 2024-02-19 at 12 19 54@2x](https://github.com/jitsucom/jitsu/assets/707733/9575eebe-6554-4f59-8673-5ce0db001b4e)

Also, which version of jitsucom/console image you're using

**Comment by hanabadler** [comment] 2024-02-20 06:14
Hi

Thanks for the response
here is the stack trace

TypeError: Cannot read properties of null (reading 'credentials')
    at s.default (http://3.XXX.XXX.16:3000/_next/static/chunks/pages/signin-ecf6422c9bf4d8d7.js:1:2894)
    at Xh (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:60992)
    at x (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:119447)
    at Vk (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:99132)
    at http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:98999
    at Jk (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:99006)
    at Ok (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:95762)
    at Hk (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:9:94318)
    at J (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:33:1364)
    at MessagePort.R (http://3.XXX.XXX.16:3000/_next/static/chunks/framework-f3379ba7fbed21eb.js:33:1894)


the console image in the docker-compose is


console:
    tty: true
    image: jitsucom/console:latest
    restart: "unless-stopped"
    platform: linux/amd64
    environment:
      ROTOR_URL: "http://rotor:3401"
      BULKER_URL: "http://bulker:3042"
      CONSOLE_RAW_AUTH_TOKENS: ${CONSOLE_TOKEN:-default}
      BULKER_AUTH_KEY: ${BULKER_TOKEN:-default}
      MIT_COMPLIANT: ${MIT_COMPLIANT:-false}
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-default}@postgres:5432/postgres?schema=newjitsu"
      REDIS_URL: "redis://default:${REDIS_PASSWORD:-default}@redis:6379"
      SEED_USER_EMAIL: ${SEED_USER_EMAIL:-}
      SEED_USER_PASSWORD: ${SEED_USER_PASSWORD:-}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SYNCS_ENABLED: ${SYNCS_ENABLED:-false}
      SYNCCTL_URL: "http://syncctl:${EXTERNAL_SYNCS_PORT:-3043}"
      SYNCCTL_AUTH_KEY: ${SYNCCTL_TOKEN:-default}
      GOOGLE_SCHEDULER_KEY: ${GOOGLE_SCHEDULER_KEY}
      JITSU_INGEST_PUBLIC_URL: "${JITSU_INGEST_PUBLIC_URL:-http://localhost:${JITSU_INGEST_PORT:-8080}/}"
      JITSU_PUBLIC_URL: "${JITSU_PUBLIC_URL:-${NEXTAUTH_URL:-http://localhost:${JITSU_UI_PORT:-3000}/}}"
      NEXTAUTH_URL: "${JITSU_PUBLIC_URL:-${NEXTAUTH_URL:-http://localhost:${JITSU_UI_PORT:-3000}/}}"
      UPDATE_DB: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://console:3000/api/healthcheck"]
      interval: 2s
      timeout: 10s
      retries: 30
    extra_hosts:
      - "syncctl:host-gateway"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "${JITSU_UI_PORT:-3000}:3000"

**Comment by hanabadler** [comment] 2024-02-26 11:28
Hi 
Any updates on this issue ?

**Comment by vklimontovich** [comment] 2024-02-26 16:51
We didn't manage to reporoduce it, but we added a few extra measures and debug logging. Would you mind trying `beta` images? Just update to a latest [docker-compose](https://github.com/jitsucom/jitsu/blob/newjitsu/docker/docker-compose.yml) from github and set `DOCKER_TAG=beta`

**Comment by vklimontovich** [comment] 2024-03-12 20:08
Closing, since the issue is most likely fixed in `2.4`

**Closed as completed** 2024-03-19 21:06 UTC
