### ISSUE TITLE
Web UI automatically logged out {"error":"token required","message":"Authorization failed: token required"}

### ISSUE THREAD

**Issue by donavan-tangible** [jitsucom/jitsu#1000] opened 2023-02-10 21:26 UTC
## Environment
```bash
version: "2.3"
networks:
  main:

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  jitsu:
    container_name: jitsu
    image: jitsucom/jitsu:beta
    environment:
      - REDIS_URL=redis://redis:6379
      #Retroactive users recognition can affect RAM significant. Read more about the solution https://jitsu.com/docs/other-features/retroactive-user-recognition
      - USER_RECOGNITION_ENABLED=false
      - USER_RECOGNITION_REDIS_URL=redis://redis_users_recognition:6380
      - TERM=xterm-256color
    depends_on:
      - redis
    volumes:
      - ./compose-data/configurator/data/logs:/home/configurator/data/logs
      - ./compose-data/server/data/logs:/home/eventnative/data/logs
      - ./compose-data/server/data/logs/events:/home/eventnative/data/logs/events
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/home/eventnative/data/airbyte
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - /root/application/my-plugins/:/home/eventnative/data/plugins/
      - /root/application/docker/eventnative.yaml:/home/eventnative/data/config/eventnative.yaml
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
      - "443:443"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:6.2.6-bullseye
    volumes:
      - ./compose-data/redis/data:/data
    restart: always
    networks:
      - main
  redis_users_recognition:
    container_name: jitsu_redis_users_recognition
    image: redis:6.2.6-bullseye
    volumes:
      - ./compose-data/redis_users_recognition/data:/data
      - ./compose-data/redis_users_recognition/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - main

volumes:
  workspace:
    name: jitsu_workspace
```

## Description
Web UI automatically logged out (ResizeObserver loop complete with undelivered notification)

## Steps to reproduce
Use lastest version of jitsu or jitsu:beta
Try to login
Create a new project / try to save a setting
You will be automatically be disconnected

## Expected behavior
Stay connected to in the web UI

## Actual behavior
The web UI always disconnect 

<img width="1273" alt="capture_d___e__cran__le_2023-02-10_a___16 16 04" src="https://user-images.githubusercontent.com/109524661/218200107-a8ea7c26-ead6-4935-b66b-0d432aefbbc6.png">
<img width="1680" alt="Capture d’écran, le 2023-02-11 à 07 22 26" src="https://user-images.githubusercontent.com/109524661/218258735-b513483b-0888-4e51-b1a5-3558624e9f0b.png">

401 error message --> {"error":"token required","message":"Authorization failed: token required"}

**Comment by absorbb** [comment] 2023-02-13 11:25
The issue was caused by custom `eventnative.yaml` mapped as a volume to joint `jitsucom/jitsu` image.
  ``` 
  volumes:
...
      - /root/application/docker/eventnative.yaml:/home/eventnative/data/config/eventnative.yaml
```

Custom config support is designed for `jitsucom/server` image.
Joint `jitsucom/jitsu`  image has UI and server tightly coupled on config level  – replacing `eventnative.yaml` may cause unexpected behavior like in this ticket.

Closing ticket.

**Closed by absorbb** 2023-02-13 11:25 UTC
