### ISSUE TITLE
Can't build from source - codegen error

### ISSUE THREAD

**Issue by keedle** [jitsucom/jitsu#970] opened 2022-09-27 16:43 UTC
## Environment

- **Deploy method**:  `built from sources`
- **Jitsu version**:  for instance `1.42.8`
- **OS**: for instance  `Ubuntu 20.04` / `Windows 10`

## Description
Can build server but having an issue building configurator.

```
$ ./local-build-configurator.sh -d false

============================================
=    Building go Configurator backend...   =
============================================

rm -f configurator
rm -rf ./build
go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1
go generate
error processing flags: flags --generate, --templates aren't supported in new config style, please use --old-style-config or update your configurationmain.go:72: running "oapi-codegen": exit status 1
Makefile:29: recipe for target 'go_generate' failed
make: *** [go_generate] Error 1
Building go configurator backend failed

```
## Steps to reproduce

follow build form source [doc ](https://jitsu.com/docs/deployment/build-from-sources)

## Expected behavior

build configurator

## Actual behavior

codegen error

**Comment by absorbb** [comment] 2022-09-30 08:47
Hi @keedle !
What version of `go` do you use?
I cannot reproduce the problem with:
`go version go1.18.4 linux/amd64` on Ubuntu 20.04
`go version go1.19.1 darwin/arm64` on Mac OS 12.6

**Comment by keedle** [comment] 2022-09-30 11:41
Hi @absorbb ,
go version go1.19.1 linux/amd64 on Ubuntu 20.04 just tried to build and it failed log attached ☹ Maybe I'm missing a step or something?

```
ubuntu@server:/var/www$ git clone https://github.com/jitsucom/jitsu.git
Receiving objects: 100% (51656/51656), 30.38 MiB | 24.23 MiB/s, done.
Resolving deltas: 100% (35665/35665), done.

ubuntu@server:/var/www$ cd jitsu/
ubuntu@server:/var/www/jitsu$ chmod +x local-build-server.sh
ubuntu@server:/var/www/jitsu$ chmod +x local-build-configurator.sh
ubuntu@server:/var/www/jitsu$ chmod +x local-build-jitsu.sh
ubuntu@server:/var/www/jitsu$

ubuntu@server:/var/www/jitsu$ go version
go version go1.19.1 linux/amd64
ubuntu@server:/var/www/jitsu$ ./local-build-server.sh -d false

=====================================
=    Downloading javascript sdk...  =
=====================================

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19913    0 19913    0     0   5337      0 --:--:--  0:00:03 --:--:--  5335

=====================================
=       Building go Server...       =
=====================================

rm -f eventnative
rm -rf ./build/dist/eventnative
rm -rf ./build/dist
echo "Using path /home/ubuntu/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin"
Using path /home/ubuntu/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
go mod download
GOARCH=amd64 go build -ldflags "-X main.commit=`git rev-parse --short HEAD` -X main.builtAt=`date -u +%FT%T.000000Z` -X main.tag=$( case master in ( master ) git describe --tags ;; ( * ) echo master ;; esac )" -o eventnative
mkdir -p ./build/dist/web/
mv eventnative ./build/dist
mkdir -p ./build/dist/web/
test -e ../javascript-sdk/lib.js && cp ../javascript-sdk/lib.js ./build/dist/web/ || echo "\n\033[31m!!! WARNING:\033[m lib.js wasn't found at ../javascript-sdk/lib.js. Please build JS SDK first, or embedded tracking will not work!\n"
mkdir -p ./build/dist/web/
cp ./web/dist/web/* ./build/dist/web/
cp ./web/welcome.html ./build/dist/web/

=====================================
=        SUCCESSFUL BUILD           =
=====================================
ubuntu@server:/var/www/jitsu$ ./local-build-configurator.sh -d false

============================================
=    Building go Configurator backend...   =
============================================

rm -f configurator
rm -rf ./build
go get github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1
go generate
error processing flags: flags --generate, --templates aren't supported in new config style, please use --old-style-config or update your configurationmain.go:72: running "oapi-codegen": exit status 1
Makefile:29: recipe for target 'go_generate' failed
make: *** [go_generate] Error 1
Building go configurator backend failed
ubuntu@server:/var/www/jitsu$
```

**Comment by absorbb** [comment] 2022-09-30 11:52
@keedle 
there may be newest version of oapi-codegen already installed on you system.
You can check with:
`oapi-codegen -version`
if it is v1.11 you can downgrade with
`go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1`
command and build jitsu.

we need to upgrade build scripts to support new version of oapi-codegen to close this ticket.

**Closed** 2022-09-30 12:22 UTC
